Add item requests and gateway
desyatov-student/java-shareit pull request #4
Opened 2024-09-25 20:23 UTC by desyatov-student

2024-09-27 08:24 UTC, tomattman requested changes
Привет
два основных момента, первый про валидацию, по условию должен быть гейтвей, он стартует как отдельное приложение, которое принимает в себя все запросы, валдиирует их и если валидно, то пересылать данные на основное сервер, следовательно валидацию можно убрать с основного сервиса, и по хорошему можно убрать зависимости от нее с этого сервиса, и гейтвей не должен зависеть от основного приложения,  у него должны быть свои дто с валидацией, и обработка всех валидаций должна быть именно на гейтвее

Второй момент по тестам, они есть, они хороши, но их слишком мало, надо добавить еще, обычно на каждый публичный метод делают по несколько тестов, следует как минимум какой то функционал покрыть полностью, и остальные уже можно чуть меньше(но только потому что это учебный проект)

2024-09-27 08:24 UTC, tomattman commented on server/src/main/java/ru/practicum/shareit/comment/dto/NewCommentRequest.java
> +    @Size(max = COMMENT_MAX_SIZE)
по условию валидация должна быть на гейтвее,
и лучше убрать зависимости от валидационных бибилиотек из всех подпроектов кроме гейтвея

2024-09-27 08:24 UTC, tomattman commented on server/src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    Collection<ItemRequest> findByAuthor_Id(Long authorId, Sort sort);
в других классах репозиториях имена не разделяются нижним подчеркиванием, тут разделяются, стоит сделать в одном стиле

2024-09-27 08:24 UTC, tomattman commented on server/src/main/java/ru/practicum/shareit/validation/CheckDateValidator.java
> +public class CheckDateValidator implements ConstraintValidator<StartBeforeEndDateValid, NewBookingRequest> {
по условию валидация должна быть на гейтвее

2024-09-27 17:39 UTC, desyatov-student commented on server/src/main/java/ru/practicum/shareit/comment/dto/NewCommentRequest.java
> +    @Size(max = COMMENT_MAX_SIZE)
Удалил из модуля сервер. Все DTO лежат в модуле dto

2024-09-28 12:45 UTC, desyatov-student commented on server/src/main/java/ru/practicum/shareit/validation/CheckDateValidator.java
> +public class CheckDateValidator implements ConstraintValidator<StartBeforeEndDateValid, NewBookingRequest> {
Это удалил все перенесено в модуль dto

2024-09-28 14:42 UTC, tomattman approved these changes
Принято

2024-10-12 16:59 UTC, merged